version: "3"

services:
  server:
    env_file:
      - ./server/.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_port: 8085
        debug_port: 9229
      #   app_db: app-db:30000
      #   app_env: alpha
    command: npm run debug
    container_name: server
    restart: always
    volumes:
      - ./server/src:/app/server/src
    ports:
      - "8085:8085"
      - "9229:9229"

  youtube:
    env_file:
      - ./plugins/youtube/.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_port: 8090
        debug_port: 9229
      #   app_db: app-db:30000
      #   app_env: alpha
    command: npm run debug
    container_name: youtube-plugin
    restart: always
    volumes:
      - ./plugins/youtube/src:/app/server/src
    ports:
      - "8090:8090"
      - "9230:9229"


  twitch:
    env_file:
      - ./plugins/twitch/.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_port: 8095
        debug_port: 9229
      #   app_db: app-db:30000
      #   app_env: alpha
    command: npm run debug
    container_name: twitch-plugin
    restart: always
    volumes:
      - ./plugins/twitch/src:/app/server/src
    ports:
      - "8095:8095"
      - "9231:9229"
    # links:
    #   - app-db
  # app-db:
  #   container_name: app-db
  #   image: mongo:3.6.5
  #   ports:
  #     - "30000:27017"
  #   volumes:
  #     - mongodata:/data/db
# volumes:
#   mongodata:
#       driver: local
